sudo: false
language: ruby

rvm:
- 2.4.1
- 2.3.4
- 2.2
- 2.1
- 2.0
- jruby-9.1.12.0
- ruby-head
- jruby-head

cache:
- bundler

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 2.0
#   fast_finish: true
